/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_cuml_ForestInference */

#ifndef _Included_ai_rapids_cuml_ForestInference
#define _Included_ai_rapids_cuml_ForestInference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_rapids_cuml_ForestInference
 * Method:    nativeInit
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_cuml_ForestInference_nativeInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     ai_rapids_cuml_ForestInference
 * Method:    nativePredict
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cuml_ForestInference_nativePredict
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_rapids_cuml_ForestInference
 * Method:    nativeLoad
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cuml_ForestInference_nativeLoad
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
